apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: lab8-app 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: lab8-app 
  template: 
    metadata: 
      labels: 
        app: lab8-app 
    spec: 
      containers: 
      - name: lab8-app 
        image: gcr.io/td-lab-489107/lab8-app:latest 
        ports: 
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
